### ISSUE TITLE
App no longer working

### ISSUE THREAD

**Issue by matthewrdunn** [zendesklabs/proactive_tickets_app#5]
In my test account when I click "Create Campaign" I just see the 3 loading dots but can't get any further.

The console shows 403 Forbidden at this endpoint:

GET https://z3nasmatthewdunn.zendesk.com/api/v2/user_views.json 403 (Forbidden)

**Comment by aculligan** [comment]
Seeing this in some accounts too.
![1462203737](https://cloud.githubusercontent.com/assets/16241656/14959185/bf06a5da-1053-11e6-8a5b-63099ba753e0.png)

**Comment by eboyle** [comment]
Looks like you don't have the customer lists feature. This app DOES require customer lists in order to work.
